on:
  schedule:
    - cron: "0 22 * * 0" # UTC Time
  workflow_dispatch:

name: Export bugphyzz 

jobs:
  export-bugphyzz:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: bugphyzzExports

      - name: Install R dependencies
        run: |
          pkgs <- c("BiocFileCache",
                    "castor",
                    "logr",
                    "phytools",
                    "purrr",
                    "tibble",
                    "tidyr",
                    "waldronlab/bugphyzzExports")
          BiocManager::install(pkgs, dependencies = TRUE)
        shell: Rscript {0}

      - name: Export bugphyzz
        run: |
          cd $GITHUB_WORKSPACE/bugphyzzExports
          rm *.gmt *.csv
          Rscript inst/scripts/export_bugphyzz.R

      - name: Commit Exports
        run: |
          cd $GITHUB_WORKSPACE/bugphyzzExports
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add *.csv *.gmt *.log
          git commit -m "Weekly export update"
          git push
